image:
  file: .gitpod.Dockerfile

tasks:
  - init: go get -v -t -d ./...

vscode:
  extensions:
    - premparihar.gotestexplorer@0.1.10:jvUM8akrQ67vQxfjaxCgCg==
    - graphql.vscode-graphql@0.3.8:jHk/gSNypa0bHc+cU2gp8w==
