// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/buildhub-gg/buildhub/build"
	"github.com/buildhub-gg/buildhub/graph"
	"github.com/buildhub-gg/buildhub/item"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func InitResolver() (*graph.Resolver, error) {
	embedItemSpecRepository, err := item.NewRepoItemSpecs()
	if err != nil {
		return nil, err
	}
	inMemoryBuildRepository := build.NewInMemoryBuildRepository()
	resolver := graph.NewResolver(embedItemSpecRepository, inMemoryBuildRepository)
	return resolver, nil
}
